### ISSUE TITLE
Issue with splitting strings with escaped characters

### ISSUE THREAD

**Issue by palesius** [CaseyPlummer/mssql-table-rebuild#1]
your existing split code will produce an incorrect result for the following input.
`SELECT * FROM [dbo].[Split]('&', 'First&"Second&T"hird&Fourth');`

Results in:
```
First

quot;Second
T
quot;hird
Fourth
```

Changing the order you handle escaping in, by putting the ampersand first seems to correct that:
```
SET @Delimiter = REPLACE(@Delimiter, '&', '&amp;')
SET @Delimiter = REPLACE(@Delimiter, '"', '&quot;')
SET @Delimiter = REPLACE(@Delimiter, '''', '&apos;')
SET @Delimiter = REPLACE(@Delimiter, '<', '&lt;')
SET @Delimiter = REPLACE(@Delimiter, '>', '&gt;')
SET @Text = REPLACE(@Text, '&', '&amp;')
SET @Text = REPLACE(@Text, '"', '&quot;')
SET @Text = REPLACE(@Text, '''', '&apos;')
SET @Text = REPLACE(@Text, '<', '&lt;')
SET @Text = REPLACE(@Text, '>', '&gt;')
```

Arguably it's not going to be a big problem with column names, but it will also split incorrectly when any escaped character (other than ampersand is included:
`SELECT * FROM [dbo].[Split](',', 'First,"Second",Third');`

Results in:
```
First
&quot;Second&quot;
Third
```

**Comment by CaseyPlummer** [comment]
Thank you. Fixed this with:
https://github.com/CaseyPlummer/mssql-table-rebuild/commit/f9753e7cca05db97aff2ff2b1508e150ac1ad3d5
